AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  EnforcedStyle: crlf

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  MinNameLength: 1
